spring:
  application:
    name: products-management
  datasource:
    url: jdbc:mysql://192.168.214.108:3306/products_management?allowPublicKeyRetrieval=true&useSSL=false
    username: yascode
    password: VGEdapIhoQnSoKC6Z2iY
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info